### PR TITLE
Update rolling logo

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

@vatanaksoytezer we need something better than this but this will do for now.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by tylerjw** [comment]
@vatanaksoytezer what do you think of merging this and then creating an issue for finding a way to create better art?

**Comment by vatanaksoytezer** [comment]
@tylerjw I am fine with dice logo, though can we change the font and color of the text? So it's more or less like foxy, and then we merge it?

**Comment by tylerjw** [comment]
> @tylerjw I am fine with dice logo, though can we change the font and color of the text? So it's more or less like foxy, and then we merge it?

I don't have the font for foxy.  Maybe the logo should just be the dice and no text?

**Comment by vatanaksoytezer** [comment]
> I don't have the font for foxy. Maybe the logo should just be the dice and no text?

I think text is nice, I can take a look at the font if you like. Or we can merge with dice only and I can send another PR for that

**Comment by AndyZe** [comment]
I'm not sure about this one. Are we going for a Stranger Things, early 90's web look?   ;)

I think the text is important, it can't be just a picure of a die.

Probably @skolk should review

**Comment by DLu** [comment]
Full

**Comment by tylerjw** [comment]
I love it

**Comment by davetcoleman** [comment]
i'm about to replace this PR

**Pull request closed without merging**
