### PR TITLE
Remove Kinetic from Dropdown

### PR DESCRIPTION
**Pull request by auman66**
### Description

Removing Kinetic from the dropdown. This will need to be done for Melodic & Noetic versions as well.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by vatanaksoytezer — APPROVED** [review]
Tested locally, looks good to me!

**Comment by vatanaksoytezer** [comment]
This PR needs to be backported to galactic and rolling branches.

**Comment by v4hn** [comment]
Is this deployed already? I can still see the link on [the website](http://moveit2_tutorials.picknik.ai/).

> This will need to be done for Melodic & Noetic versions as well.

Eventually, yes. But not as long as users are still looking for it there. :)

**Comment by vatanaksoytezer** [comment]
@v4hn we currently on deploy from Foxy branch until Tyler and I figure out how we should deploy from multiple branches using gh-pages (soon-ish). So until #179 gets merged it will not be deployed to the website.

**Pull request merged**
