### PR TITLE
[galactic] Update black version

### PR DESCRIPTION
**Pull request by stephanie-eng**
Should fix the error in formatting CI - see https://github.com/ros-planning/moveit2_tutorials/pull/344

### CODE REVIEW

**Review by AndyZe — APPROVED** [review]

**Comment by AndyZe** [comment]
I was actually looking at this earlier. I think you need to add the github permissions like this:

https://github.com/ros-planning/moveit2/pull/1210

**Comment by stephanie-eng** [comment]
> I was actually looking at this earlier. I think you need to add the github permissions like this:
> 
> [ros-planning/moveit2#1210](https://github.com/ros-planning/moveit2/pull/1210)

I saw this error being commented about [here](https://github.com/actions/checkout/issues/760), which should be fixed with a new version of checkout, hopefully. I just made a new PR #354 to see if that works.

**Review by rhaschke — APPROVED** [review]
Although this PR doesn't solve the "git safe directory" issue (not sure this was intended?),
it actually solves issues with black auto-formatting. Thus I approve.
@stephanie-eng, please be more specific in your PR description.

**Comment by stephanie-eng** [comment]
Apologies, see updated description. This was not intended to fix the git safe directory issue, just the error from black in the formatting check.

**Pull request merged**
