### PR TITLE
Add pytorch to Isaac sim tutorial

### PR DESCRIPTION
**Pull request by PeterMitrano**
Expands the existing Isaac sim tutorial to enable using pytorch inside the container along side moveit. This work is in support of World MoveIt Day

https://github.com/orgs/ros-planning/projects/6?pane=issue&itemId=24675770

Currently the scope is quite limited, the goal is simply that you can import pytorch and use the GPU from within the `demo_isaac` container, and that the new environment has (1) some object the robot can push around and (2) working RGB & Depth images

### CODE REVIEW

**Comment by PeterMitrano** [comment]
One TODO is to update the video link in the RST file, but I'm waiting on Shane to upload it to the PickNik youtube

**Review by MarqRazz — COMMENTED** [review]
Tested with 2.0 and 2.1.  Are you planning on adding anything to the tutorial to tell the user that Pytorch is installed and ready to use?

Suggest adding the camera subscribers to the Rviz config.

**Comment by PeterMitrano** [comment]
I've incorporated the fixes from #674 and they seem to be working. I'd like to include some more details about pytorch/python but the python API doesn't seem to exist inside the docker. I thought it would, since I think we're using the `main` branch of moveit, but perhaps I've done something wrong or it's out of date? I see this version of moveit-core: `2.7.3-31-g226f81c6e-2023.05.15.02.34`

**Comment by tylerjw** [comment]
@PeterMitrano would you mind checking out the PR #694 which is on the main branch and confirm that we didn't miss anything and that it works as you'd expect?

**Comment by PeterMitrano** [comment]
Yea sure! I'm at ICRA this week so pretty busy, but I'll try!

**Comment by MarqRazz** [comment]
WMD is over and I'm pretty sure we got everything from this PR.

**Pull request closed without merging**
