### PR TITLE
:memo: Make Galactic branch the default

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

This will make the galactic branch of this website the default landing page.

### CODE REVIEW

**Comment by AndyZe** [comment]
Let's take a moment and look at David Lu's distro starts before merging this. I'll do it soon .

**Comment by tylerjw** [comment]
This one? https://metrics.ros.org/rosdistro_rosdistro.html

There are more users than foxy or rolling per that.

**Comment by AndyZe** [comment]
This graph shows Foxy bring about 2X more popular than Galactic.

https://metrics.ros.org/packages_rosdistro.html

Meh, whatever.

**Review by AndyZe — APPROVED** [review]

**Comment by tylerjw** [comment]
Do you actually want to encourage people to use foxy?  We are library developers.  Do you want MoveIt 2 to be based on foxy?

**Comment by AndyZe** [comment]
My point is, Galactic isn't used much. It probably never will be because it's non-LTS. That's all.

**Comment by AndyZe** [comment]
It's fine. A 2X factor is actually better than I expected.

**Pull request merged**
