### PR TITLE
Use ros2 branch of moveit_task_constructor instead of humble

### PR DESCRIPTION
**Pull request by lukas-jung**
### Description

The humble branch has been removed.
See https://github.com/ros-planning/moveit_task_constructor/issues/480

### CODE REVIEW

**Review by JafarAbdi — APPROVED** [review]

**Review by sea-bass — APPROVED** [review]
Thank you!

**Comment by sea-bass** [comment]
Ah, a few more updates are needed here due to renamed variables in MTC. I can take a look later if someone doesn't get to it first.

**Comment by rhaschke** [comment]
Looks like deleting the `humble` branch in MTC was a mistake. As the `ros2` branch ran successfully with the docker image `humble-source` (https://github.com/ros-planning/moveit_task_constructor/pull/470), I thought that the humble branch wouldn't be necessary anymore. However, it is for use with the MoveIt `humble` branch used for the image `humble-release`, which is used here.
@ros-planning/moveit-core-contributors, does any maintainer still have the humble branch locally to restore it?
This would avoid redoing the humble modifications...

**Comment by sea-bass** [comment]
@rhaschke I didn't have it locally, but I just pushed a slightly modified version of the `ros2` branch to `humble` that compiles and runs for me against `moveit2_tutorials`. Please check it:

https://github.com/ros-planning/moveit_task_constructor/tree/humble

**Comment by sea-bass** [comment]
NOTE: I found a separate issue in humble that requires this backport: https://github.com/ros-planning/moveit2_tutorials/pull/722

**Comment by rhaschke** [comment]
Thanks, @sea-bass. I did the same in parallel and also added a CI build for `humble-release`. Closing this PR as obsolete.

**Comment by lukas-jung** [comment]
@sea-bass @rhaschke

The commits of the original humble branch still exist:
[293898690e323176c0f5c2fbe223affa53bde462](https://github.com/ros-planning/moveit_task_constructor/commit/293898690e323176c0f5c2fbe223affa53bde462)

This is HEAD of my local copy. Cloned July 24.

It might be helpful for users if the new version is rebased to the old version so they can update it with git pull.

**Comment by rhaschke** [comment]
@lukas-jung, you should be able to fast-forward from the specified commit to the new humble branch:
image

**Pull request closed without merging**
