### PR TITLE
Remove move_group as a namespace for ompl configs

### PR DESCRIPTION
**Pull request by JafarAbdi**
### Description

Another solution to https://github.com/ros-planning/moveit2/pull/524

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
Neither https://github.com/ros-planning/moveit2/pull/524 nor this seems to work for me in `demo.launch.py` @JafarAbdi

**Comment by JafarAbdi** [comment]
> Neither [ros-planning/moveit2#524](https://github.com/ros-planning/moveit2/pull/524) nor this seems to work for me in `demo.launch.py` @JafarAbdi

You need to start `panda_hand_controller` as shown in https://github.com/ros-planning/moveit2_tutorials/pull/93

**Comment by henningkayser** [comment]
So this might be the desirable approach to #524 since the parameters are using the `move_group` node name implicitly.

**Comment by vatanaksoytezer** [comment]
> You need to start `panda_hand_controller` as shown in #93

Adding `panda_hand_controller` makes the tutorial working for me!

**Review by vatanaksoytezer — APPROVED** [review]

**Comment by henningkayser** [comment]
https://github.com/ros-planning/moveit2/pull/524 fixed this

**Pull request closed without merging**
