### PR TITLE
Request help with tutorial porting, don't turn people away

### PR DESCRIPTION
**Pull request by davetcoleman**
@bostoncleek let's avoid saying stuff in open source is "not ready for contributions", we pretty much always want help and comments like that quickly get outdated.

### CODE REVIEW

**Review by JafarAbdi — APPROVED** [review]

**Comment by auman66** [comment]
Rebased. Good to go!

**Comment by bostoncleek** [comment]
> @bostoncleek let's avoid saying stuff in open source is "not ready for contributions", we pretty much always want help and comments like that quickly get outdated.

@davetcoleman What did is the context for this? I don't recall saying anything along these lines.

**Comment by davetcoleman** [comment]
@bostoncleek I looked at ``git blame`` and thought that was your comment, my bad if it wasn't!

**Comment by davetcoleman** [comment]
@bostoncleek sorry for assuming it was you, but in my defense this was what ``git blame`` showed before this PR:
image

I now see you had only edited the [existing text](https://github.com/ros-planning/moveit2_tutorials/commit/00e756c20a5b55d2923039ec86899591d9f9c8ce)

**Comment by bostoncleek** [comment]
@davetcoleman ok no worries

**Pull request merged**
